from django.db import migrations

# Raw SQL migration to recreate all non-Django tables from Table DDL.txt.
# Note: Django needs the database (`mathrubhumi`) to already exist before running migrations.
# If it does not, create it once manually with: CREATE DATABASE mathrubhumi WITH ENCODING 'UTF8';

FORWARD_SQL = r"""
-- Sequence needed by sale_rt_items.id default
CREATE SEQUENCE IF NOT EXISTS public.sales_rt_items_id_seq;

CREATE TABLE IF NOT EXISTS public.agents (
    id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
    agent_nm varchar(100) NOT NULL,
    address1 varchar(50) NULL,
    address2 varchar(50) NULL,
    city varchar(30) NULL,
    telephone varchar(30) NULL,
    contact varchar(30) NULL,
    email varchar(50) NULL,
    CONSTRAINT agents_pk PRIMARY KEY (id),
    CONSTRAINT agents_unique UNIQUE (agent_nm)
);


CREATE TABLE IF NOT EXISTS public.authors (
    id int4 DEFAULT 0 NOT NULL,
    author_nm varchar(80) NOT NULL,
    address1 varchar(50) NULL,
    address2 varchar(50) NULL,
    city varchar(30) NULL,
    telephone varchar(30) NULL,
    contact varchar(30) NULL,
    mail_id varchar(50) NULL,
    CONSTRAINT authors_pk PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.branches (
    id int2 DEFAULT 0 NOT NULL,
    branches_nm varchar(50) NOT NULL,
    CONSTRAINT branches_pk PRIMARY KEY (id),
    CONSTRAINT branches_unique UNIQUE (branches_nm)
);


CREATE TABLE IF NOT EXISTS public.categories (
    id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
    category_nm varchar(50) NOT NULL,
    CONSTRAINT categories_pk PRIMARY KEY (id),
    CONSTRAINT categories_unique UNIQUE (category_nm)
);


CREATE TABLE IF NOT EXISTS public.company (
    id int2 DEFAULT 0 NOT NULL,
    company_name text NOT NULL,
    address1 varchar(100) NOT NULL,
    address2 varchar(100) NOT NULL,
    city_with_pin varchar(50) NOT NULL,
    email varchar(100) NOT NULL,
    contact_nos varchar(100) NOT NULL,
    gstin varchar(15) NULL,
    pan varchar(10) NULL,
    cin varchar(25) NULL,
    for_whom varchar(100) NOT NULL,
    CONSTRAINT company_pk PRIMARY KEY (id),
    CONSTRAINT company_unique UNIQUE (company_name)
);


CREATE TABLE IF NOT EXISTS public.cr_customers (
    id int4 NOT NULL,
    customer_nm varchar(100) NOT NULL,
    customer_type int2 DEFAULT 0 NOT NULL,
    address_1 varchar(70) NULL,
    address_2 varchar(70) NULL,
    city varchar(30) NULL,
    telephone varchar(30) NULL,
    email_id varchar(50) NULL,
    gstin varchar(15) NULL,
    debit numeric(10, 3) DEFAULT 0.00 NOT NULL,
    credit numeric(10, 3) DEFAULT 0.00 NOT NULL,
    credit_limit numeric(10, 3) DEFAULT 0.00 NOT NULL,
    credit_days int2 DEFAULT 0 NOT NULL,
    "class" int2 DEFAULT 0 NOT NULL,
    shipping_address_1 varchar(50) NULL,
    shipping_address_2 varchar(50) NULL,
    shipping_city varchar(30) NULL,
    shipping_telephone varchar(30) NULL,
    contact_person varchar(50) NULL,
    CONSTRAINT cr_customers_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.cr_realisation (
    company_id int2 NOT NULL,
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    receipt_no int4 NULL,
    entry_date date NULL,
    customer_id int4 DEFAULT 0 NOT NULL,
    amount numeric(10, 2) NULL,
    a_type int2 NULL,
    bank varchar(50) NULL,
    chq_dd_no varchar(15) NULL,
    note1 varchar(50) NULL,
    cancelled int2 DEFAULT 0 NOT NULL,
    exhibition_id int2 DEFAULT 0 NOT NULL,
    user_id int2 DEFAULT 0 NOT NULL,
    printed int2 DEFAULT 0 NOT NULL,
    CONSTRAINT cr_realisation_unique UNIQUE (company_id, id)
);


CREATE TABLE IF NOT EXISTS public.currencies (
    id int2 NOT NULL,
    currency_name varchar(25) NOT NULL,
    exchange_rate numeric(8, 2) NOT NULL,
    CONSTRAINT currencies_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.last_values (
    company_id int2 DEFAULT 0 NOT NULL,
    fin_year bpchar(4) DEFAULT '0000'::bpchar NOT NULL,
    code bpchar(12) NOT NULL,
    "last_value" int4 DEFAULT 0 NOT NULL,
    CONSTRAINT control_unique UNIQUE (company_id, fin_year, code)
);


CREATE TABLE IF NOT EXISTS public.places (
    id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
    place_nm varchar(30) NOT NULL,
    CONSTRAINT places_pk PRIMARY KEY (id),
    CONSTRAINT places_unique UNIQUE (place_nm)
);


CREATE TABLE IF NOT EXISTS public.pp_books (
    company_id int2 NOT NULL,
    id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
    code varchar(12) NOT NULL,
    nos int2 NULL,
    face_value numeric(8, 2) NULL,
    reg_start_date date NULL,
    reg_end_date date NULL,
    date_of_release date NULL,
    notes varchar(100) NULL,
    closed int2 NOT NULL,
    pp_book_firm_id int2 NOT NULL,
    nos_ex int2 DEFAULT 5000 NOT NULL,
    product_id int4 DEFAULT 0 NOT NULL,
    inserted timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pp_books_unique UNIQUE (company_id, id)
);


CREATE TABLE IF NOT EXISTS public.pp_customer_books (
    company_id int2 DEFAULT 0 NOT NULL,
    id int4 DEFAULT 0 NOT NULL,
    pp_customer_id int4 DEFAULT 0 NOT NULL,
    pp_book_id int2 DEFAULT 0 NOT NULL,
    reg_no varchar(10) NOT NULL,
    copies int2 DEFAULT 0 NOT NULL,
    CONSTRAINT unq_pp_customer_books UNIQUE (company_id, reg_no)
);


CREATE TABLE IF NOT EXISTS public.pp_customers (
    id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
    pp_customer_nm varchar(100) NOT NULL,
    address1 varchar(50) NULL,
    address2 varchar(50) NULL,
    city varchar(30) NULL,
    telephone varchar(30) NULL,
    contact varchar(30) NULL,
    email varchar(50) NULL,
    company_id int2 DEFAULT 0 NOT NULL,
    pin bpchar(6) NULL,
    CONSTRAINT pp_customer_pk PRIMARY KEY (id),
    CONSTRAINT pp_customer_unique UNIQUE (pp_customer_nm)
);


CREATE TABLE IF NOT EXISTS public.pp_receipts (
    company_id int2 DEFAULT 0 NOT NULL,
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    receipt_no int4 DEFAULT 0 NOT NULL,
    entry_date date NULL,
    pp_customer_id int2 DEFAULT 0 NOT NULL,
    pp_book_id int4 DEFAULT 0 NOT NULL,
    amount numeric(8, 2) DEFAULT 0.00 NOT NULL,
    r_type int2 NOT NULL,
    a_type int2 NOT NULL,
    bank varchar(50) NULL,
    chq_dd_no varchar(15) NULL,
    installments varchar(10) NULL,
    note1 varchar(50) NULL,
    customer_id int2 DEFAULT 0 NOT NULL,
    agent_id int2 DEFAULT 0 NOT NULL,
    cancelled int2 DEFAULT 0 NOT NULL,
    exhibition_id int2 DEFAULT 0 NOT NULL,
    user_id int2 DEFAULT 0 NOT NULL,
    printed int2 DEFAULT 0 NOT NULL,
    pp_customer_book_id int4 DEFAULT 0 NOT NULL,
    CONSTRAINT pk_pp_receipts PRIMARY KEY (company_id, id)
);


CREATE TABLE IF NOT EXISTS public.privilegers (
    id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
    privileger_nm varchar(100) NOT NULL,
    address1 varchar(50) NULL,
    address2 varchar(50) NULL,
    city varchar(30) NULL,
    telephone varchar(30) NULL,
    contact varchar(30) NULL,
    email varchar(50) NULL,
    CONSTRAINT privilegers_pk PRIMARY KEY (id),
    CONSTRAINT privilegers_unique UNIQUE (privileger_nm)
);


CREATE TABLE IF NOT EXISTS public.publishers (
    id int2 DEFAULT 0 NOT NULL,
    publisher_nm varchar(100) NOT NULL,
    address1 varchar(50) NULL,
    address2 varchar(50) NULL,
    city varchar(30) NULL,
    telephone varchar(30) NULL,
    contact varchar(30) NULL,
    email varchar(50) NULL,
    own int2 DEFAULT 0 NOT NULL,
    max_discount_p numeric(5, 2) DEFAULT 0.00 NOT NULL,
    CONSTRAINT publishers_pk PRIMARY KEY (id),
    CONSTRAINT publishers_unique UNIQUE (publisher_nm)
);


CREATE TABLE IF NOT EXISTS public.purchase (
    id serial4 NOT NULL,
    entry_date date DEFAULT CURRENT_DATE NOT NULL,
    invoice_date date DEFAULT CURRENT_DATE NOT NULL,
    supplier_id int4 DEFAULT 0 NOT NULL,
    nett numeric(10, 2) DEFAULT 0.00 NOT NULL,
    invoice_no varchar(25) NULL,
    inward_type int2 DEFAULT 0 NOT NULL,
    transaction_type int2 DEFAULT 0 NOT NULL,
    notes varchar(100) NULL,
    gross numeric(10, 2) DEFAULT 0.00 NOT NULL,
    p_breakup_id1 int2 DEFAULT 0 NOT NULL,
    p_breakup_amount1 numeric(8, 2) DEFAULT 0.00 NOT NULL,
    p_breakup_id2 int2 DEFAULT 0 NOT NULL,
    p_breakup_amount2 numeric(8, 2) DEFAULT 0.00 NOT NULL,
    p_breakup_id3 int2 DEFAULT 0 NOT NULL,
    p_breakup_amount3 numeric(8, 2) DEFAULT 0.00 NOT NULL,
    p_breakup_id4 int2 DEFAULT 0 NOT NULL,
    p_breakup_amount4 numeric(8, 2) DEFAULT 0.00 NOT NULL,
    user_id int2 DEFAULT 0 NOT NULL,
    branch_id int2 DEFAULT 0 NOT NULL,
    company_id int2 DEFAULT 1 NOT NULL,
    purchase_no int2 DEFAULT 0 NOT NULL,
    CONSTRAINT purchase_unique UNIQUE (company_id, id)
);


CREATE TABLE IF NOT EXISTS public.purchase_breakups (
    id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
    breakup_nm varchar(50) DEFAULT '.'::character varying NOT NULL,
    CONSTRAINT newtable_pk PRIMARY KEY (id),
    CONSTRAINT newtable_unique UNIQUE (breakup_nm)
);


CREATE TABLE IF NOT EXISTS public.purchase_items (
    id serial4 NOT NULL,
    purchase_id int4 DEFAULT 0 NOT NULL,
    title_id int4 DEFAULT 0 NOT NULL,
    rate numeric(8, 2) DEFAULT 0.00 NOT NULL,
    exchange_rate numeric(8, 2) DEFAULT 0.00 NOT NULL,
    discount_p numeric(5, 2) DEFAULT 0.00 NOT NULL,
    discount_a numeric(8, 2) DEFAULT 0.00 NOT NULL,
    quantity numeric(10, 3) DEFAULT 0.00 NOT NULL,
    closing numeric(10, 3) DEFAULT 0.00 NOT NULL,
    currency_id int2 DEFAULT 0 NOT NULL,
    sgst numeric(5, 2) DEFAULT 0.00 NOT NULL,
    cgst numeric(5, 2) DEFAULT 0.00 NOT NULL,
    isbn varchar(15) NULL,
    company_id int2 DEFAULT 1 NOT NULL,
    origin_company_id int2 DEFAULT 0 NOT NULL,
	origin_purchase_id int4 DEFAULT 0 NOT NULL,
	origin_purchase_items_id int4 DEFAULT 0 NOT NULL,
	purchase_cost numeric(8, 2) DEFAULT 0.00 NOT NULL,
    CONSTRAINT purchase_items_unique UNIQUE (company_id, id)
);


CREATE TABLE IF NOT EXISTS public.purchase_rt (
    company_id int2 DEFAULT 0 NOT NULL,
    id serial4 NOT NULL,
    purchase_rt_no int2 DEFAULT 0 NOT NULL,
    entry_date date DEFAULT CURRENT_DATE NOT NULL,
    nett numeric(10, 2) DEFAULT 0 NOT NULL,
    supplier_id int4 NOT NULL,
    narration varchar(100) DEFAULT '.'::character varying NOT NULL,
    pr_type int2 DEFAULT 0 NULL,
    gross numeric(10, 2) DEFAULT 0 NOT NULL,
    inter_state int2 DEFAULT 0 NOT NULL,
    user_id int2 DEFAULT 0 NULL,
    CONSTRAINT purchase_rt_unique UNIQUE (company_id, id)
);


CREATE TABLE IF NOT EXISTS public.purchase_rt_items (
    company_id int2 DEFAULT 0 NOT NULL,
    parent_id int4 DEFAULT 0 NOT NULL,
    id serial4 NOT NULL,
    title_id int4 DEFAULT 0 NOT NULL,
    quantity numeric(10, 3) DEFAULT 0.00 NOT NULL,
    rate numeric(8, 2) DEFAULT 0.00 NOT NULL,
    exchange_rate numeric(8, 2) DEFAULT 0.00 NOT NULL,
    adjusted_amount numeric(10, 2) DEFAULT 0.00 NOT NULL,
    discount numeric(5, 2) DEFAULT 0.00 NOT NULL,
    line_value numeric(10, 3) DEFAULT 0.00 NOT NULL,
    purchase_det_id int4 DEFAULT 0 NOT NULL,
    purchase_company_id int2 DEFAULT 0 NOT NULL,
	purchase_id int4 DEFAULT 0 NOT NULL,
	currency_id int2 DEFAULT 0 NOT NULL,
    CONSTRAINT purchase_rt_items_unique UNIQUE (company_id, parent_id, id)
);


CREATE TABLE IF NOT EXISTS public.remittance (
    company_id int2 NOT NULL,
    id int4 NOT NULL,
    remittance_no int4 NULL,
    entry_date date NULL,
    a_type int2 DEFAULT 0 NOT NULL,
    bank_id int2 DEFAULT 0 NOT NULL,
    amount numeric(10, 2) DEFAULT 0 NULL,
    ac_receipt_id int4 DEFAULT 0 NOT NULL,
    note1 varchar(50) NULL,
    cancelled int2 DEFAULT 0 NOT NULL,
    exhibition_id int2 DEFAULT 0 NOT NULL,
    c_name varchar(80) DEFAULT '.'::character varying NOT NULL,
    account_id int4 DEFAULT 0 NOT NULL,
    customer_id int4 DEFAULT 0 NOT NULL,
    pp_customer_id int4 DEFAULT 0 NOT NULL,
    user_id int2 DEFAULT 0 NOT NULL,
    printed int2 DEFAULT 0 NOT NULL,
    CONSTRAINT pk_remittance PRIMARY KEY (company_id, id)
);


CREATE TABLE IF NOT EXISTS public.royalty_recipients (
    id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
    royalty_recipient_nm varchar(100) NOT NULL,
    address1 varchar(50) NULL,
    address2 varchar(50) NULL,
    city varchar(30) NULL,
    telephone varchar(30) NULL,
    contact varchar(30) NULL,
    email varchar(50) NULL,
    CONSTRAINT royalty_recipients_pk PRIMARY KEY (id),
    CONSTRAINT royalty_recipients_unique UNIQUE (royalty_recipient_nm)
);


CREATE TABLE IF NOT EXISTS public.sale_cash_modes (
    sale_cash_modeid int4 NOT NULL,
    sale_cash_mode varchar(15) NULL,
    CONSTRAINT sale_cash_modes_unique UNIQUE (sale_cash_modeid),
    CONSTRAINT sale_cash_modes_unique_1 UNIQUE (sale_cash_mode)
);


CREATE TABLE IF NOT EXISTS public.sale_classes (
    id int2 NOT NULL,
    class_nm varchar(30) NOT NULL,
    CONSTRAINT sale_classes_pk PRIMARY KEY (id),
    CONSTRAINT sale_classes_unique_class_nm UNIQUE (class_nm)
);


CREATE TABLE IF NOT EXISTS public.sale_items (
    id serial4 NOT NULL,
    sale_id int4 DEFAULT 0 NOT NULL,
    quantity numeric(10, 3) DEFAULT 0.00 NOT NULL,
    rate numeric(10, 3) DEFAULT 0.00 NOT NULL,
    line_value numeric(10, 3) DEFAULT 0.00 NOT NULL,
    discount_p numeric DEFAULT 0.00 NOT NULL,
    title_id int4 DEFAULT 0.00 NOT NULL,
    exchange_rate numeric(8, 2) DEFAULT 0.00 NOT NULL,
    currency_id int2 DEFAULT 0 NOT NULL,
    allocated_bill_discount numeric(10, 3) DEFAULT 0.00 NOT NULL,
    tax numeric(5, 2) DEFAULT 0.00 NOT NULL,
    purchase_item_id int4 DEFAULT 0 NOT NULL,
    company_id int2 DEFAULT 1 NOT NULL,
    CONSTRAINT sale_items_unique UNIQUE (company_id, id)
);


CREATE TABLE IF NOT EXISTS public.sale_rt_items (
    company_id int2 DEFAULT 0 NOT NULL,
    parent_id int4 DEFAULT 0 NOT NULL,
    id int4 DEFAULT nextval('sales_rt_items_id_seq'::regclass) NOT NULL,
    title_id int4 DEFAULT 0 NOT NULL,
    quantity numeric(10, 3) DEFAULT 0 NOT NULL,
    rate numeric(8, 2) DEFAULT 0 NOT NULL,
    tax numeric(5, 2) DEFAULT 0 NOT NULL,
    exchange_rate numeric(8, 2) DEFAULT 0 NOT NULL,
    discount_p numeric(5, 2) DEFAULT 0.00 NULL,
    discount_a numeric(8, 2) DEFAULT 0 NOT NULL,
    discount numeric(8, 2) DEFAULT 0.00 NULL,
    sale_det_id int4 DEFAULT 0 NOT NULL,
    line_value numeric(10, 2) DEFAULT 0.00 NOT NULL,
    purchase_det_id int4 DEFAULT 0 NOT NULL
);


CREATE TABLE IF NOT EXISTS public.sale_types (
    sale_typeid int4 NOT NULL,
    sale_type varchar(15) NULL,
    CONSTRAINT sale_types_unique UNIQUE (sale_typeid)
);


CREATE TABLE IF NOT EXISTS public.sales (
    id serial4 NOT NULL,
    customer_nm varchar(100) NULL,
    billing_address text NULL,
    sale_date date NULL,
    mobile_number varchar(20) NULL,
    "type" int2 NULL,
    "mode" int2 NULL,
    "class" int2 NULL,
    cancel int2 NULL,
    bill_discount numeric NULL,
    note_1 text NULL,
    note_2 text NULL,
    bill_amount numeric NULL,
    bill_discount_amount float8 NULL,
    gross float8 NULL,
    round_off float8 NULL,
    freight_postage numeric NULL,
    processing_charge numeric NULL,
    bill_no varchar(15) DEFAULT '000000000000000'::character varying NOT NULL,
    cr_customer_id int4 DEFAULT 0 NOT NULL,
    company_id int2 DEFAULT 1 NOT NULL,
    user_id int2 DEFAULT 0 NOT NULL,
    agent_id int2 DEFAULT 0 NOT NULL,
    branch_id int2 DEFAULT 0 NOT NULL,
    CONSTRAINT sales_unique UNIQUE (company_id, id)
);


CREATE TABLE IF NOT EXISTS public.sales_rt (
    company_id int2 DEFAULT 0 NOT NULL,
    id serial4 NOT NULL,
    sales_rt_no int4 DEFAULT 0 NOT NULL,
    entry_date date DEFAULT CURRENT_DATE NOT NULL,
    s_type int2 DEFAULT 0 NOT NULL,
    cash int2 DEFAULT 0 NOT NULL,
    cash_customer varchar(100) DEFAULT '.'::character varying NOT NULL,
    narration varchar(100) NULL,
    nett numeric(10, 2) DEFAULT 0 NOT NULL,
    gross numeric(10, 2) DEFAULT 0 NOT NULL,
    discount_a numeric(8, 2) DEFAULT 0 NOT NULL,
    discount_p numeric(5, 2) DEFAULT 0 NOT NULL,
    rounded_off numeric(2, 2) DEFAULT 0 NOT NULL,
    user_id int2 DEFAULT 0 NULL,
    cr_customer_id int4 DEFAULT 0 NULL
);


CREATE TABLE IF NOT EXISTS public.sub_categories (
    id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
    sub_category_nm varchar(50) NOT NULL,
    CONSTRAINT sub_categories_pk PRIMARY KEY (id),
    CONSTRAINT sub_categories_unique UNIQUE (sub_category_nm)
);


CREATE TABLE IF NOT EXISTS public.suppliers (
    id int4 DEFAULT 0 NOT NULL,
    supplier_nm varchar(100) NOT NULL,
    address_1 varchar(70) NULL,
    address_2 varchar(70) NULL,
    city varchar(30) NULL,
    telephone varchar(30) NULL,
    email_id varchar(50) NULL,
    gstin varchar(15) NULL,
    debit numeric(10, 3) DEFAULT 0.00 NOT NULL,
    credit numeric(10, 3) DEFAULT 0.00 NOT NULL,
    credit_days int2 DEFAULT 0 NOT NULL,
    contact_person varchar(50) NULL,
    CONSTRAINT suppliers_pk PRIMARY KEY (id),
    CONSTRAINT suppliers_unique_supplier_nm UNIQUE (supplier_nm)
);


CREATE TABLE IF NOT EXISTS public.titles (
    id int4 NOT NULL,
    title varchar(150) NULL,
    author_id int4 DEFAULT 0 NOT NULL,
    language_id int2 DEFAULT 0 NOT NULL,
    title_m varchar(150) NULL,
    rate numeric(8, 2) DEFAULT 0.00 NOT NULL,
    stock numeric(12, 3) DEFAULT 0.000 NOT NULL,
    tax numeric(5, 2) DEFAULT 0.00 NOT NULL,
    isbn varchar(15) NULL,
    publisher_id int2 NULL,
    translator_id int4 NULL,
    category_id int2 DEFAULT 0 NOT NULL,
    sub_category_id int2 DEFAULT 0 NOT NULL,
    ro_level int2 DEFAULT 0 NOT NULL,
    ro_quantity int2 DEFAULT 0 NOT NULL,
    dn_level int2 DEFAULT 0 NOT NULL,
    sap_code varchar(20) NULL,
    location_id int2 DEFAULT 0 NOT NULL,
    CONSTRAINT titles_pk PRIMARY KEY (id)
);

-- Attach the sequence to the sale_rt_items.id column so it is dropped with the table
ALTER SEQUENCE public.sales_rt_items_id_seq OWNED BY public.sale_rt_items.id;
"""

REVERSE_SQL = r"""
DROP TABLE IF EXISTS public.titles CASCADE;
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public.sub_categories CASCADE;
DROP TABLE IF EXISTS public.sales_rt CASCADE;
DROP TABLE IF EXISTS public.sales CASCADE;
DROP TABLE IF EXISTS public.sale_types CASCADE;
DROP TABLE IF EXISTS public.sale_rt_items CASCADE;
DROP TABLE IF EXISTS public.sale_items CASCADE;
DROP TABLE IF EXISTS public.sale_classes CASCADE;
DROP TABLE IF EXISTS public.sale_cash_modes CASCADE;
DROP TABLE IF EXISTS public.royalty_recipients CASCADE;
DROP TABLE IF EXISTS public.remittance CASCADE;
DROP TABLE IF EXISTS public.purchase_rt_items CASCADE;
DROP TABLE IF EXISTS public.purchase_rt CASCADE;
DROP TABLE IF EXISTS public.purchase_items CASCADE;
DROP TABLE IF EXISTS public.purchase_breakups CASCADE;
DROP TABLE IF EXISTS public.purchase CASCADE;
DROP TABLE IF EXISTS public.publishers CASCADE;
DROP TABLE IF EXISTS public.privilegers CASCADE;
DROP TABLE IF EXISTS public.pp_receipts CASCADE;
DROP TABLE IF EXISTS public.pp_customers CASCADE;
DROP TABLE IF EXISTS public.pp_customer_books CASCADE;
DROP TABLE IF EXISTS public.pp_books CASCADE;
DROP TABLE IF EXISTS public.places CASCADE;
DROP TABLE IF EXISTS public.last_values CASCADE;
DROP TABLE IF EXISTS public.currencies CASCADE;
DROP TABLE IF EXISTS public.cr_realisation CASCADE;
DROP TABLE IF EXISTS public.cr_customers CASCADE;
DROP TABLE IF EXISTS public.company CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.branches CASCADE;
DROP TABLE IF EXISTS public.authors CASCADE;
DROP TABLE IF EXISTS public.agents CASCADE;
DROP SEQUENCE IF EXISTS public.sales_rt_items_id_seq CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
