# Generated by Django 5.2.1 on 2025-12-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_purchase_origin_to_purchase_rt_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBranch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("branch_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_branches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="userbranch",
            index=models.Index(fields=["user", "branch_id"], name="accounts_us_user_id_d6d8ed_idx"),
        ),
        migrations.AddIndex(
            model_name="userbranch",
            index=models.Index(fields=["branch_id"], name="accounts_us_branch__2a0b33_idx"),
        ),
        migrations.AddConstraint(
            model_name="userbranch",
            constraint=models.UniqueConstraint(fields=("user", "branch_id"), name="uniq_user_branch"),
        ),
    ]

